---
title: "Explortory Anlaysis"
subtitle: "EDA"
output: github_document
---

Setting options for plots & embedding

```{r, include = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6, 
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continous.colour = "viridis",
  ggplot2.continous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Load the weather data

```{r, include = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>% #the lubridate package, a tidyverse adjacent package, which take the "floor" of the date and pulls it to the nearest month (so all dates in Jan-xx-2001, will be noted as Jan 01 - 01)
  select(name, id, everything())

weather_df
```


## `group_by`

```{r}
weather_df %>% 
  group_by(name, month) %>% #3 names & 12 months, so should have around 36 groups
  ungroup() #undoing the grouping you did ... you can also ungroup one variable at a time ungroup(name)
```


